"""
NLP Pipeline — optimised for 4 GB VRAM / 16 GB RAM systems.

Model choices (4GB-VRAM-friendly):
  NER       : d4data/biomedical-ner-all          (~420 MB, CPU)
  Report gen: microsoft/BioGPT  (base, not Large) (~350 MB, CPU)
              Falls back to a structured template if GPU VRAM < threshold.
  Summarizer: sshleifer/distilbart-cnn-12-6       (~310 MB, CPU/GPU)
              (replaces facebook/bart-large-cnn ~1.6 GB)
  QA        : deepset/biobert-base-cased-v1.2-squad2 (~420 MB, CPU)

Total NLP RAM footprint: ~1.5 GB  (vs ~8 GB with the Large models)
All models run on CPU to keep VRAM free for the vision pipeline.
"""

import torch
from functools import lru_cache
from datetime import datetime

# ── Always use CPU for NLP so VRAM stays free for vision models ──────────────
_NLP_DEVICE = -1   # -1 = CPU in HuggingFace pipeline API


# ── Lazy singletons ───────────────────────────────────────────────────────────

@lru_cache(maxsize=1)
def _get_ner():
    from transformers import pipeline
    print("[NLP] Loading biomedical NER …")
    return pipeline(
        "ner",
        model="d4data/biomedical-ner-all",
        aggregation_strategy="simple",
        device=_NLP_DEVICE,
    )


@lru_cache(maxsize=1)
def _get_report_gen():
    from transformers import pipeline
    print("[NLP] Loading BioGPT (base) for report generation …")
    return pipeline(
        "text-generation",
        model="microsoft/BioGPT",   # base ≈ 350 MB  (not BioGPT-Large ≈ 1.5 GB)
        device=_NLP_DEVICE,
    )


@lru_cache(maxsize=1)
def _get_summarizer():
    from transformers import pipeline
    print("[NLP] Loading DistilBART for summarization …")
    return pipeline(
        "summarization",
        model="sshleifer/distilbart-cnn-12-6",  # ≈ 310 MB  (not bart-large-cnn ≈ 1.6 GB)
        device=_NLP_DEVICE,
    )


@lru_cache(maxsize=1)
def _get_qa():
    from transformers import pipeline
    print("[NLP] Loading BioBERT QA …")
    return pipeline(
        "question-answering",
        model="deepset/biobert-base-cased-v1.2-squad2",
        device=_NLP_DEVICE,
    )


# ── Public API ────────────────────────────────────────────────────────────────

def extract_symptoms(text: str) -> dict:
    """Run biomedical NER and return recognised symptom tokens."""
    if not text or not text.strip():
        return {"symptoms": [], "entities": [], "raw": text}
    ner      = _get_ner()
    entities = ner(text)
    symptoms = [e["word"] for e in entities if e["score"] > 0.70]
    return {
        "symptoms" : symptoms,
        "entities" : [
            {"word": e["word"], "entity_group": e["entity_group"],
             "score": round(e["score"], 3)}
            for e in entities
        ],
        "raw": text,
    }


def _template_report(
    scan_type: str, body_part: str, diagnosis: str,
    confidence: float, severity: str,
    symptoms: list[str], patient_name: str,
) -> str:
    """
    Lightweight structured report — no model required.
    Used as primary path (fast) and as fallback if BioGPT fails.
    """
    symptom_str  = ", ".join(symptoms) if symptoms else "not reported"
    today        = datetime.now().strftime("%d %B %Y")
    severity_rec = {
        "HIGH"    : "Urgent specialist review recommended within 24 hours.",
        "MODERATE": "Follow-up with treating physician within 1 week.",
        "LOW"     : "Routine follow-up as clinically indicated.",
    }.get(severity, "Clinical correlation recommended.")

    return (
        f"RADIOLOGY REPORT\n"
        f"{'─'*48}\n"
        f"Patient      : {patient_name}\n"
        f"Date         : {today}\n"
        f"Study        : {scan_type.replace('_', ' ').title()} of {body_part.title()}\n"
        f"Symptoms     : {symptom_str}\n"
        f"{'─'*48}\n\n"
        f"FINDINGS:\n"
        f"The {scan_type.replace('_', ' ')} demonstrates imaging findings "
        f"most consistent with {diagnosis} (model confidence: {confidence}%). "
        f"Severity has been assessed as {severity}.\n\n"
        f"IMPRESSION:\n"
        f"1. {diagnosis} — {severity} severity ({confidence}% confidence).\n"
        f"2. {severity_rec}\n"
        f"3. This report is AI-generated and must be reviewed by a qualified radiologist.\n\n"
        f"{'─'*48}\n"
        f"Generated by MedVision AI · For research use only\n"
    )


def generate_report(
    scan_type: str,
    body_part: str,
    diagnosis: str,
    confidence: float,
    severity: str,
    symptoms: list[str],
    patient_name: str = "Anonymous",
    use_biogpt: bool  = False,   # opt-in; template is used by default (fast)
) -> str:
    """
    Generate a structured radiology report.

    use_biogpt=False (default): returns a clean template report instantly.
    use_biogpt=True           : appends BioGPT-generated clinical impression.
    """
    template = _template_report(
        scan_type, body_part, diagnosis,
        confidence, severity, symptoms, patient_name,
    )

    if not use_biogpt:
        return template

    # BioGPT augmentation (optional, adds ~10–30 s on CPU)
    prompt = (
        f"Radiology impression for {scan_type} showing {diagnosis} "
        f"with {severity} severity:\n"
    )
    try:
        gen = _get_report_gen()
        out = gen(
            prompt,
            max_new_tokens=100,
            do_sample=False,
            repetition_penalty=1.3,
        )
        biogpt_text = out[0]["generated_text"].replace(prompt, "").strip()
        return template + f"\nAI CLINICAL NOTE (BioGPT):\n{biogpt_text}\n"
    except Exception as exc:
        return template   # silently fall back to template


def summarize_report(report_text: str) -> str:
    """
    Summarize a radiology report to ≤80 tokens using DistilBART.
    Falls back to the first 2 sentences if the model fails.
    """
    if not report_text:
        return ""
    truncated = report_text[:2000]
    try:
        summ = _get_summarizer()
        out  = summ(truncated, max_length=80, min_length=25, do_sample=False)
        return out[0]["summary_text"]
    except Exception:
        sentences = truncated.split(". ")
        return ". ".join(sentences[:2]) + "."


def answer_question(question: str, context: str) -> dict:
    """Answer a free-text medical question using BioBERT QA."""
    if not question or not context:
        return {
            "answer"     : "Please provide both a question and a report context.",
            "confidence" : 0.0,
        }
    try:
        qa     = _get_qa()
        result = qa(question=question, context=context)
        return {
            "answer"     : result["answer"],
            "confidence" : round(result["score"] * 100, 1),
        }
    except Exception as exc:
        return {
            "answer"     : f"Could not answer: {exc}",
            "confidence" : 0.0,
        }
